if(screen.width>=1500)
{
    document.write("<style>body{zoom:80%}</style>");
}
if(screen.width>=2000)
{
    document.write("<style>body{zoom:50%}</style>");
}
if(screen.width>=2500)
{
    document.write("<style>body{zoom:35%}</style>");
}