let shopItemsData = [
  {
    id: "tower",
    name: "Cat Tower",
    price: 60,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/tower.jpg",
  },
  {
    id: "ball",
    name: "Ball",
    price: 50,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/ball.jpg",
  },
  {
    id: "plush",
    name: "Bird Plush",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/bird_plush.jpg",
  },
  {
    id: "birdfood",
    name: "Bird Food",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/birdfood.jpg",
  },
  {
    id: "catfood",
    name: "Cat Food",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/catfood.jpg",
  },
  {
    id: "chew",
    name: "Chew Toy",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/chewtoy.jpg",
  },
  {
    id: "frisbee",
    name: "Frisbee",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/dog_frisbee.jpg",
  },
  {
    id: "nest",
    name: "Bird Swing and Nest",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/nest.jpg",
  },

  {
    id: "stand",
    name: "Play Stand",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/playstand.jpg",
  },
  {
    id: "dogfood",
    name: "Dog Food",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/dogfood.jpg",
  },
  {
    id: "swing",
    name: "Swing",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/swing.jpg",
  },
  {
    id: "fishfood",
    name: "Fish Food",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/fishfood.jpg",
  },
];
